# Generated by Django 4.2.13 on 2024-11-13 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('enquiry_name', models.CharField(max_length=150)),
                ('enquiry_email', models.EmailField(max_length=150)),
                ('enquiry_company', models.CharField(blank=True, max_length=150)),
                ('enquiry_occasion', models.CharField(blank=True, choices=[('AW', 'After Work'), ('KO', 'Work Kick Off'), ('BP', 'Birthday Party'), ('SP', 'Surprise Party'), ('O', 'Other')], max_length=30)),
                ('enquiry_theme', models.CharField(blank=True, choices=[('TAQ', 'Three Amigos Quiz'), ('ST', 'Specific/Themed Quiz')], max_length=20)),
                ('enquiry_location', models.CharField(blank=True, choices=[('TS', 'The Snug (12-20ppl)'), ('WP', 'Wirströms Pub (25-100ppl)'), ('W', 'At your workplace'), ('OL', 'Other Location')], max_length=30)),
                ('enquiry_number_of_quizzers', models.IntegerField(blank=True, null=True)),
                ('enquiry_when', models.DateTimeField(default=django.utils.timezone.now)),
                ('enquiry_information', models.TextField(blank=True, max_length=1000)),
                ('enquiry_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
