# Generated by Django 4.2.13 on 2024-06-25 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('company', models.CharField(max_length=150)),
                ('reason', models.CharField(choices=[('AW', 'After Work'), ('KO', 'Work Kick Off'), ('BP', 'Birthday Party'), ('SP', 'Surprise Party'), ('O', 'Other')], max_length=30)),
                ('quiz_type', models.CharField(choices=[('TAQ', 'Three Amigos Quiz'), ('S/T', 'Specific/Themed Quiz')], max_length=20)),
                ('quizzers', models.IntegerField(max_length=3)),
                ('where', models.CharField(choices=[('TS', 'The Snug (15-25ppl)'), ('WP', 'Wirströms Pub (25-100ppl)'), ('W', 'At your workplace'), ('OL', 'Other Location')], max_length=30)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
