# Generated by Django 4.2.13 on 2024-06-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='quizzers',
            field=models.IntegerField(),
        ),
    ]
