# Generated by Django 4.2.13 on 2024-11-08 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_quizzers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('enquiry_name', models.CharField(max_length=150)),
                ('enquiry_email', models.EmailField(max_length=150)),
                ('enquiry_company', models.CharField(blank=True, max_length=150)),
                ('enquiry_occasion', models.CharField(blank=True, choices=[('AW', 'After Work'), ('KO', 'Work Kick Off'), ('BP', 'Birthday Party'), ('SP', 'Surprise Party'), ('O', 'Other')], max_length=30)),
                ('enquiry_theme', models.CharField(blank=True, choices=[('TAQ', 'Three Amigos Quiz'), ('ST', 'Specific/Themed Quiz')], max_length=20)),
                ('enquiry_number_of_quizzers', models.IntegerField(blank=True, null=True)),
                ('enquiry_location', models.CharField(blank=True, choices=[('TS', 'The Snug (12-20ppl)'), ('WP', 'Wirströms Pub (25-100ppl)'), ('W', 'At your workplace'), ('OL', 'Other Location')], max_length=30)),
                ('enquiry_when', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('enquiry_information', models.TextField(blank=True)),
                ('enquiry_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='company',
            new_name='booking_company',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='booking_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='quizzers',
            new_name='booking_number_of_quizzers',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='sent',
            new_name='booking_sent',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='when',
            new_name='booking_when',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='quiz_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='where',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_location',
            field=models.CharField(choices=[('TS', 'The Snug (12-20ppl)'), ('WP', 'Wirströms Pub (25-100ppl)'), ('W', 'At your workplace'), ('OL', 'Other Location')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_occasion',
            field=models.CharField(choices=[('AW', 'After Work'), ('KO', 'Work Kick Off'), ('BP', 'Birthday Party'), ('SP', 'Surprise Party'), ('O', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_theme',
            field=models.CharField(choices=[('TAQ', 'Three Amigos Quiz'), ('ST', 'Specific/Themed Quiz')], max_length=20, null=True),
        ),
    ]
