# Generated by Django 4.2.13 on 2024-11-08 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_enquiry_rename_company_booking_booking_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_location',
            field=models.CharField(choices=[('TS', 'The Snug (12-20ppl)'), ('WP', 'Wirströms Pub (25-100ppl)'), ('W', 'At your workplace'), ('OL', 'Other Location')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_occasion',
            field=models.CharField(choices=[('AW', 'After Work'), ('KO', 'Work Kick Off'), ('BP', 'Birthday Party'), ('SP', 'Surprise Party'), ('O', 'Other')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_theme',
            field=models.CharField(choices=[('TAQ', 'Three Amigos Quiz'), ('ST', 'Specific/Themed Quiz')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
