# Generated by Django 4.2.13 on 2024-11-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_information',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
