# Generated by Django 4.2.13 on 2024-11-12 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_enquiry_enquiry_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
