# Generated by Django 4.2.13 on 2024-11-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_enquiry_enquiry_when'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
