# Generated by Django 4.2.13 on 2024-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_delete_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_information',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
